use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Bijwerken via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex-gebruiksmonitor",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    codex_model: "Codex",
    settings: "Instellingen",
    usage_display: "Gebruiksweergave",
    usage_windows: "Gebruiksvensters",
    used_usage: "Gebruikt",
    remaining_usage: "Resterend",
    start_with_windows: "Opstarten met Windows",
    reset_position: "Positie herstellen",
    compact_mode: "Compacte modus",
    language: "Taal",
    system_default: "Systeemstandaard",
    check_for_updates: "Controleren op updates",
    checking_for_updates: "Controleren op updates...",
    updates: "Updates",
    update_in_progress: "Er is al een updatecontrole bezig.",
    up_to_date: "Je gebruikt al de nieuwste versie.",
    up_to_date_short: "Up-to-date",
    update_failed: "Automatisch bijwerken mislukt",
    applying_update: "Update wordt toegepast...",
    update_to: "Bijwerken naar",
    update_available: "Update beschikbaar",
    update_prompt_now: "Versie {version} is beschikbaar. Wil je nu bijwerken?",
    exit: "Afsluiten",
    show_widget: "Widget tonen",
    show_5hour_window: "Limiet van 5 uur",
    show_7day_window: "Limiet van 7 dagen",
    no_data: "Geen gegevens",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    hour_suffix: "u",
    minute_suffix: "m",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "CodexRadar inschakelen",
    refresh_codex_radar: "Aanbevelingsgegevens nu vernieuwen",
    view_codex_radar_website: "Website bekijken",
    codex_radar_consent_title: "CodexRadar inschakelen?",
    codex_radar_consent_body: "Wanneer ingeschakeld maakt deze app periodiek verbinding met CodexRadar voor aanbevelingsgegevens van de community.\r\n\r\nUw Codex Token, gebruiksgegevens en projectinhoud worden niet verzonden. Zoals bij elk websiteverzoek kan CodexRadar wel normale netwerkinformatie zien, zoals uw IP-adres en User-Agent.\r\n\r\nCodexRadar inschakelen?",
    radar_speed_recommendation: "Snelheid",
    radar_smart_recommendation: "Intelligentie",
    radar_community_daily: "Dagelijkse community",
    radar_daily_recommendation: "Dagelijks",
    radar_hard_problem: "Moeilijk probleem",
    radar_tooltip_header:
        "CodexRadar · Klik driemaal op de taakbalkwidget om de website te openen\r\n{age} geleden bijgewerkt\r\nVolgende update: {next_update}",
    radar_cached_warning: "Cachegegevens, mogelijk verouderd",
    radar_loading: "CodexRadar-aanbevelingen ophalen...",
    radar_data_unavailable: "Gegevens tijdelijk niet beschikbaar",
    radar_fetch_error: "Kan CodexRadar-aanbevelingen niet ophalen",
    radar_no_eligible: "Geen combinatie met IQ ≥ 90",
};
