use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Bijwerken via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex-gebruiksmonitor",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    codex_model: "Codex",
    settings: "Instellingen",
    usage_display: "Gebruiksweergave",
    usage_windows: "Gebruiksvensters",
    used_usage: "Gebruikt",
    remaining_usage: "Resterend",
    start_with_windows: "Opstarten met Windows",
    reset_position: "Positie herstellen",
    compact_mode: "Compacte modus",
    language: "Taal",
    system_default: "Systeemstandaard",
    check_for_updates: "Controleren op updates",
    checking_for_updates: "Controleren op updates...",
    updates: "Updates",
    update_in_progress: "Er is al een updatecontrole bezig.",
    up_to_date: "Je gebruikt al de nieuwste versie.",
    up_to_date_short: "Up-to-date",
    update_failed: "Automatisch bijwerken mislukt",
    applying_update: "Update wordt toegepast...",
    update_to: "Bijwerken naar",
    update_available: "Update beschikbaar",
    update_prompt_now: "Versie {version} is beschikbaar. Wil je nu bijwerken?",
    exit: "Afsluiten",
    show_widget: "Widget tonen",
    show_5hour_window: "Limiet van 5 uur (verouderd)",
    show_7day_window: "Limiet van 7 dagen",
    no_data: "Geen gegevens",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    second_suffix: "s",
};
