use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Monitor",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    codex_model: "Codex",
    settings: "Settings",
    usage_display: "Usage Display",
    usage_windows: "Usage windows",
    used_usage: "Used",
    remaining_usage: "Remaining",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    compact_mode: "Compact Mode",
    language: "Language",
    system_default: "System Default",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Show Widget",
    show_5hour_window: "5-hour limit (deprecated)",
    show_7day_window: "7-day limit",
    no_data: "No data",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    hour_suffix: "h",
    minute_suffix: "m",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "Enable CodexRadar",
    refresh_codex_radar: "Refresh recommendation data now",
    view_codex_radar_website: "View website",
    codex_radar_consent_title: "Enable CodexRadar?",
    codex_radar_consent_body: "When enabled, this app periodically connects to CodexRadar for community recommendation data.\r\n\r\nIt does not send your Codex Token, usage data, or project content. As with any website request, CodexRadar can still see routine network information such as your IP address and User-Agent.\r\n\r\nEnable CodexRadar?",
    radar_speed_recommendation: "Speed",
    radar_smart_recommendation: "Smart",
    radar_daily_development: "Daily development",
    radar_intelligence_weighted: "IQ-first",
    radar_tooltip_header:
        "CodexRadar · Updated {age} ago · Non-personalized community recommendation",
    radar_cached_warning: "Cached data · May be outdated",
    radar_loading: "Fetching CodexRadar recommendations...",
    radar_data_unavailable: "Data temporarily unavailable",
    radar_fetch_error: "Unable to fetch CodexRadar recommendations",
    radar_no_eligible: "No combination with IQ ≥ 90",
};
