use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mettre à jour avec WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Moniteur d'utilisation Codex",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    codex_model: "Codex",
    settings: "Paramètres",
    usage_display: "Affichage de l’utilisation",
    usage_windows: "Fenêtres d’utilisation",
    used_usage: "Utilisé",
    remaining_usage: "Restant",
    start_with_windows: "Démarrer avec Windows",
    reset_position: "Réinitialiser la position",
    compact_mode: "Mode compact",
    language: "Langue",
    system_default: "Par défaut du système",
    check_for_updates: "Vérifier les mises à jour",
    checking_for_updates: "Vérification des mises à jour...",
    updates: "Mises à jour",
    update_in_progress: "Une vérification de mise à jour est déjà en cours.",
    up_to_date: "Vous utilisez déjà la version la plus récente.",
    up_to_date_short: "À jour",
    update_failed: "Impossible d'effectuer la mise à jour automatiquement",
    applying_update: "Application de la mise à jour...",
    update_to: "Mettre à jour vers",
    update_available: "Mise à jour disponible",
    update_prompt_now: "La version {version} est disponible. Voulez-vous mettre à jour maintenant ?",
    exit: "Quitter",
    show_widget: "Afficher le widget",
    show_5hour_window: "Limite de 5 heures (obsolète)",
    show_7day_window: "Limite de 7 jours",
    no_data: "Aucune donnée",
    session_window: "5h",
    weekly_window: "7d",
    now: "maintenant",
    hour_suffix: "h",
    minute_suffix: "m",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "Activer CodexRadar",
    refresh_codex_radar: "Actualiser les recommandations maintenant",
    view_codex_radar_website: "Voir le site web",
    codex_radar_consent_title: "Activer CodexRadar ?",
    codex_radar_consent_body: "Lorsqu'elle est activée, cette application se connecte périodiquement à CodexRadar pour obtenir les recommandations de la communauté.\r\n\r\nElle n'envoie ni votre Codex Token, ni vos données d'utilisation, ni le contenu de vos projets. Comme pour toute requête web, CodexRadar peut toutefois voir des informations réseau courantes telles que votre adresse IP et votre User-Agent.\r\n\r\nActiver CodexRadar ?",
    radar_speed_recommendation: "Vitesse",
    radar_smart_recommendation: "Intelligence",
    radar_daily_development: "Recommandations pour le développement quotidien",
    radar_intelligence_weighted: "Priorité IQ",
    radar_tooltip_header:
        "CodexRadar · Mis à jour il y a {age} · Conseil communautaire non personnalisé",
    radar_cached_warning: "Données en cache · Potentiellement obsolètes",
    radar_loading: "Récupération des recommandations CodexRadar...",
    radar_data_unavailable: "Données temporairement indisponibles",
    radar_fetch_error: "Impossible de récupérer les recommandations CodexRadar",
    radar_no_eligible: "Aucune combinaison avec IQ ≥ 90",
};
