use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mit WinGet aktualisieren";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex-Nutzungsmonitor",
    refresh: "Aktualisieren",
    update_frequency: "Aktualisierungsintervall",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    codex_model: "Codex",
    settings: "Einstellungen",
    usage_display: "Nutzungsanzeige",
    usage_windows: "Nutzungsfenster",
    used_usage: "Verwendet",
    remaining_usage: "Verbleibend",
    start_with_windows: "Mit Windows starten",
    reset_position: "Position zurücksetzen",
    compact_mode: "Kompaktmodus",
    language: "Sprache",
    system_default: "Systemstandard",
    check_for_updates: "Nach Updates suchen",
    checking_for_updates: "Suche nach Updates...",
    updates: "Updates",
    update_in_progress: "Eine Update-Prüfung läuft bereits.",
    up_to_date: "Sie verwenden bereits die neueste Version.",
    up_to_date_short: "Aktuell",
    update_failed: "Automatisches Update war nicht möglich",
    applying_update: "Update wird installiert...",
    update_to: "Aktualisieren auf",
    update_available: "Update verfügbar",
    update_prompt_now: "Version {version} ist verfügbar. Möchten Sie jetzt aktualisieren?",
    exit: "Beenden",
    show_widget: "Widget anzeigen",
    show_5hour_window: "5-Stunden-Limit (veraltet)",
    show_7day_window: "7-Tage-Limit",
    no_data: "Keine Daten",
    session_window: "5h",
    weekly_window: "7d",
    now: "jetzt",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Fuhren Sie 'codex' in einem Terminal aus und folgen Sie den Anmeldeanweisungen. Aktualisieren oder starten Sie diese App anschliessend neu.",
    second_suffix: "s",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "CodexRadar aktivieren",
    refresh_codex_radar: "Empfehlungsdaten jetzt aktualisieren",
    view_codex_radar_website: "Website anzeigen",
    codex_radar_consent_title: "CodexRadar aktivieren?",
    codex_radar_consent_body: "Wenn aktiviert, verbindet sich diese App regelmäßig mit CodexRadar, um Community-Empfehlungsdaten abzurufen.\r\n\r\nIhr Codex Token, Nutzungsdaten und Projektinhalte werden nicht gesendet. Wie bei jeder Website-Anfrage kann CodexRadar jedoch übliche Netzwerkinformationen wie Ihre IP-Adresse und den User-Agent sehen.\r\n\r\nCodexRadar aktivieren?",
    radar_recommendation: "Radar-Empfehlung",
    radar_iq_per_dollar: "IQ/$",
    radar_intelligence_weighted: "IQ-priorisiert",
    radar_tooltip_header:
        "CodexRadar · Vor {age} aktualisiert · Nicht personalisierte Community-Empfehlung",
    radar_cached_warning: "Zwischengespeicherte Daten · Möglicherweise veraltet",
    radar_loading: "CodexRadar-Empfehlungen werden abgerufen...",
    radar_data_unavailable: "Daten vorübergehend nicht verfügbar",
    radar_fetch_error: "CodexRadar-Empfehlungen konnten nicht abgerufen werden",
    radar_no_eligible: "Keine Kombination mit IQ ≥ 90",
};
