use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet で更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex 使用量モニター",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    codex_model: "Codex",
    settings: "設定",
    usage_display: "使用量表示",
    usage_windows: "使用量ウィンドウ",
    used_usage: "使用済み",
    remaining_usage: "残り",
    start_with_windows: "Windows と同時に開始",
    reset_position: "位置をリセット",
    compact_mode: "コンパクトモード",
    language: "言語",
    system_default: "システム既定",
    check_for_updates: "更新を確認",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "ウィジェットを表示",
    show_5hour_window: "5時間の上限（非推奨）",
    show_7day_window: "7日間の上限",
    no_data: "データなし",
    session_window: "5h",
    weekly_window: "7d",
    now: "今",
    hour_suffix: "時間",
    minute_suffix: "分",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "CodexRadar を有効にする",
    refresh_codex_radar: "推奨データを今すぐ更新",
    view_codex_radar_website: "ウェブサイトを表示",
    codex_radar_consent_title: "CodexRadar を有効にしますか？",
    codex_radar_consent_body: "有効にすると、このアプリはコミュニティの推奨データを取得するため、CodexRadar に定期的に接続します。\r\n\r\nCodex Token、使用量データ、プロジェクトの内容は送信されません。通常のウェブサイトへのリクエストと同様に、CodexRadar は IP アドレスや User-Agent などの一般的なネットワーク情報を確認できます。\r\n\r\nCodexRadar を有効にしますか？",
    radar_recommendation: "レーダー推奨",
    radar_iq_per_dollar: "IQ/$",
    radar_intelligence_weighted: "IQ重視",
    radar_tooltip_header: "CodexRadar · {age}前に更新 · 非パーソナライズのコミュニティ推奨",
    radar_cached_warning: "キャッシュデータ · 古い可能性があります",
    radar_loading: "CodexRadar の推奨データを取得中...",
    radar_data_unavailable: "データを一時的に利用できません",
    radar_fetch_error: "CodexRadar の推奨データを取得できません",
    radar_no_eligible: "IQ ≥ 90 の組み合わせはありません",
};
