use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet으로 업데이트";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex 사용량 모니터",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    codex_model: "Codex",
    settings: "설정",
    usage_display: "사용량 표시",
    usage_windows: "사용량 기간",
    used_usage: "사용됨",
    remaining_usage: "남음",
    start_with_windows: "Windows 시작 시 자동 실행",
    reset_position: "위치 초기화",
    compact_mode: "컴팩트 모드",
    language: "언어",
    system_default: "시스템 기본값",
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    exit: "종료",
    show_widget: "위젯 표시",
    show_5hour_window: "5시간 한도(사용 중단 예정)",
    show_7day_window: "7일 한도",
    no_data: "데이터 없음",
    session_window: "5시간",
    weekly_window: "7일",
    now: "지금",
    hour_suffix: "시간",
    minute_suffix: "분",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "CodexRadar 사용",
    refresh_codex_radar: "추천 데이터 지금 새로 고침",
    view_codex_radar_website: "웹사이트 보기",
    codex_radar_consent_title: "CodexRadar를 사용하시겠습니까?",
    codex_radar_consent_body: "사용하면 이 앱이 커뮤니티 추천 데이터를 가져오기 위해 CodexRadar에 정기적으로 연결합니다.\r\n\r\nCodex Token, 사용량 데이터 또는 프로젝트 콘텐츠는 전송하지 않습니다. 일반적인 웹사이트 요청과 마찬가지로 CodexRadar는 IP 주소와 User-Agent 같은 일반 네트워크 정보를 볼 수 있습니다.\r\n\r\nCodexRadar를 사용하시겠습니까?",
    radar_recommendation: "레이더 추천",
    radar_iq_per_dollar: "IQ/$",
    radar_intelligence_weighted: "IQ 우선",
    radar_tooltip_header: "CodexRadar · {age} 전에 업데이트 · 개인화되지 않은 커뮤니티 추천",
    radar_cached_warning: "캐시된 데이터 · 오래되었을 수 있음",
    radar_loading: "CodexRadar 추천 데이터를 가져오는 중...",
    radar_data_unavailable: "데이터를 일시적으로 사용할 수 없음",
    radar_fetch_error: "CodexRadar 추천 데이터를 가져올 수 없음",
    radar_no_eligible: "IQ ≥ 90 조합 없음",
};
