use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Atualizar via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de uso do Codex",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    codex_model: "Codex",
    settings: "Configurações",
    usage_display: "Exibição de Uso",
    usage_windows: "Janelas de uso",
    used_usage: "Usado",
    remaining_usage: "Restante",
    start_with_windows: "Iniciar com o Windows",
    reset_position: "Redefinir Posição",
    compact_mode: "Modo Compacto",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    check_for_updates: "Busca atualizações",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Exibir Widget",
    show_5hour_window: "Limite de 5 horas (obsoleto)",
    show_7day_window: "Limite de 7 dias",
    no_data: "Sem dados",
    session_window: "5h",
    weekly_window: "7d",
    now: "agora",
    hour_suffix: "h",
    minute_suffix: "m",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "Ativar CodexRadar",
    refresh_codex_radar: "Atualizar recomendações agora",
    view_codex_radar_website: "Ver site",
    codex_radar_consent_title: "Ativar CodexRadar?",
    codex_radar_consent_body: "Quando ativado, este aplicativo se conecta periodicamente ao CodexRadar para obter recomendações da comunidade.\r\n\r\nEle não envia seu Codex Token, dados de uso ou conteúdo de projetos. Como em qualquer solicitação a um site, o CodexRadar ainda pode ver informações comuns de rede, como seu endereço IP e User-Agent.\r\n\r\nAtivar CodexRadar?",
    radar_speed_recommendation: "Velocidade",
    radar_smart_recommendation: "Inteligência",
    radar_community_daily: "Recomendação diária da comunidade",
    radar_daily_recommendation: "Recomendação diária",
    radar_hard_problem: "Problema difícil",
    radar_tooltip_header:
        "CodexRadar · Clique três vezes no widget da barra de tarefas para abrir o site\r\nAtualizado há {age}\r\nPróxima atualização: {next_update}",
    radar_cached_warning: "Dados em cache, podem estar desatualizados",
    radar_loading: "Buscando recomendações do CodexRadar...",
    radar_data_unavailable: "Dados temporariamente indisponíveis",
    radar_fetch_error: "Não foi possível buscar recomendações do CodexRadar",
    radar_no_eligible: "Nenhuma combinação com IQ ≥ 90",
};
