use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Atualizar via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de uso do Codex",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    codex_model: "Codex",
    settings: "Configurações",
    usage_display: "Exibição de Uso",
    usage_windows: "Janelas de uso",
    used_usage: "Usado",
    remaining_usage: "Restante",
    start_with_windows: "Iniciar com o Windows",
    reset_position: "Redefinir Posição",
    compact_mode: "Modo Compacto",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    check_for_updates: "Busca atualizações",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Exibir Widget",
    show_5hour_window: "Limite de 5 horas (obsoleto)",
    show_7day_window: "Limite de 7 dias",
    no_data: "Sem dados",
    session_window: "5h",
    weekly_window: "7d",
    now: "agora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
};
