use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Монитор использования Codex",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    codex_model: "Codex",
    settings: "Настройки",
    usage_display: "Отображение использования",
    usage_windows: "Окна использования",
    used_usage: "Использовано",
    remaining_usage: "Осталось",
    start_with_windows: "Запускать вместе с Windows",
    reset_position: "Сбросить позицию",
    compact_mode: "Компактный режим",
    language: "Язык",
    system_default: "Системный по умолчанию",
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Показать виджет",
    show_5hour_window: "Лимит на 5 часов (устарел)",
    show_7day_window: "Лимит на 7 дней",
    no_data: "Нет данных",
    session_window: "5ч",
    weekly_window: "7д",
    now: "сейчас",
    hour_suffix: "ч",
    minute_suffix: "м",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "Включить CodexRadar",
    refresh_codex_radar: "Обновить рекомендации сейчас",
    view_codex_radar_website: "Открыть сайт",
    codex_radar_consent_title: "Включить CodexRadar?",
    codex_radar_consent_body: "После включения приложение будет периодически подключаться к CodexRadar для получения рекомендаций сообщества.\r\n\r\nCodex Token, данные об использовании и содержимое проектов не отправляются. Как и при любом запросе к сайту, CodexRadar может видеть обычные сетевые сведения, например IP-адрес и User-Agent.\r\n\r\nВключить CodexRadar?",
    radar_speed_recommendation: "Скорость",
    radar_smart_recommendation: "Интеллект",
    radar_daily_development: "Рекомендации для повседневной разработки",
    radar_intelligence_weighted: "Приоритет IQ",
    radar_tooltip_header:
        "CodexRadar · Обновлено {age} назад · Неперсонализированная рекомендация сообщества",
    radar_cached_warning: "Данные из кэша · Могли устареть",
    radar_loading: "Получение рекомендаций CodexRadar...",
    radar_data_unavailable: "Данные временно недоступны",
    radar_fetch_error: "Не удалось получить рекомендации CodexRadar",
    radar_no_eligible: "Нет комбинаций с IQ ≥ 90",
};
