use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex 用量监控",
    refresh: "刷新",
    update_frequency: "更新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    codex_model: "Codex",
    settings: "设置",
    usage_display: "用量显示",
    usage_windows: "用量窗口",
    used_usage: "已使用",
    remaining_usage: "剩余",
    start_with_windows: "开机时启动",
    reset_position: "重置位置",
    compact_mode: "紧凑模式",
    language: "语言",
    system_default: "系统默认",
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "已有更新检查正在进行中。",
    up_to_date: "您已是最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新到",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "退出",
    show_widget: "显示小工具",
    show_5hour_window: "5 小时限额（已弃用）",
    show_7day_window: "7 天限额",
    no_data: "无数据",
    session_window: "5h",
    weekly_window: "7d",
    now: "现在",
    hour_suffix: "时",
    minute_suffix: "分",
    codex_token_expired_title: "Codex 身份验证错误",
    codex_token_expired_body:
        "请在终端中运行 'codex'，并按登录提示操作。完成后，请刷新或重新启动此应用程序。",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "启用 CodexRadar",
    refresh_codex_radar: "立即刷新推荐数据",
    view_codex_radar_website: "查看网站",
    codex_radar_consent_title: "启用 CodexRadar？",
    codex_radar_consent_body: "启用后，本应用将定期访问 CodexRadar，以获取社区推荐数据。\r\n\r\n请求不会发送 Codex Token、用量数据或项目内容。与普通网站请求一样，CodexRadar 仍可看到 IP 地址、User-Agent 等常规网络信息。\r\n\r\n是否启用 CodexRadar？",
    radar_recommendation: "雷达推荐",
    radar_iq_per_dollar: "IQ/$",
    radar_intelligence_weighted: "偏智力",
    radar_tooltip_header: "CodexRadar · {age}前更新 · 非个性化社区推荐",
    radar_cached_warning: "缓存数据 · 可能已过期",
    radar_loading: "正在获取雷达推荐数据...",
    radar_data_unavailable: "数据暂不可用",
    radar_fetch_error: "雷达推荐数据获取异常",
    radar_no_eligible: "暂无符合 IQ ≥ 90 的组合",
};
