use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex 用量监控",
    refresh: "刷新",
    update_frequency: "更新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    codex_model: "Codex",
    settings: "设置",
    usage_display: "用量显示",
    usage_windows: "用量窗口",
    used_usage: "已使用",
    remaining_usage: "剩余",
    start_with_windows: "开机时启动",
    reset_position: "重置位置",
    compact_mode: "紧凑模式",
    language: "语言",
    system_default: "系统默认",
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "已有更新检查正在进行中。",
    up_to_date: "您已是最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新到",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "退出",
    show_widget: "显示小工具",
    show_5hour_window: "5 小时限额（已弃用）",
    show_7day_window: "7 天限额",
    no_data: "无数据",
    session_window: "5h",
    weekly_window: "7d",
    now: "现在",
    day_suffix: "天",
    hour_suffix: "时",
    minute_suffix: "分",
    codex_token_expired_title: "Codex 身份验证错误",
    codex_token_expired_body:
        "请在终端中运行 'codex'，并按登录提示操作。完成后，请刷新或重新启动此应用程序。",
    second_suffix: "秒",
};
