use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Actualizar con WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de uso de Codex",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    codex_model: "Codex",
    settings: "Configuración",
    usage_display: "Visualización de uso",
    usage_windows: "Ventanas de uso",
    used_usage: "Usado",
    remaining_usage: "Restante",
    start_with_windows: "Iniciar con Windows",
    reset_position: "Restablecer posición",
    compact_mode: "Modo compacto",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    check_for_updates: "Buscar actualizaciones",
    checking_for_updates: "Buscando actualizaciones...",
    updates: "Actualizaciones",
    update_in_progress: "Ya hay una comprobación de actualización en curso.",
    up_to_date: "Ya tienes la versión más reciente.",
    up_to_date_short: "Actualizado",
    update_failed: "No se pudo actualizar automáticamente",
    applying_update: "Aplicando actualización...",
    update_to: "Actualizar a",
    update_available: "Actualización disponible",
    update_prompt_now: "La versión {version} está disponible. ¿Quieres actualizar ahora?",
    exit: "Salir",
    show_widget: "Mostrar widget",
    show_5hour_window: "Límite de 5 horas (obsoleto)",
    show_7day_window: "Límite de 7 días",
    no_data: "Sin datos",
    session_window: "5h",
    weekly_window: "7d",
    now: "ahora",
    hour_suffix: "h",
    minute_suffix: "m",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "Activar CodexRadar",
    refresh_codex_radar: "Actualizar recomendaciones ahora",
    view_codex_radar_website: "Ver sitio web",
    codex_radar_consent_title: "¿Activar CodexRadar?",
    codex_radar_consent_body: "Al activarlo, esta aplicación se conectará periódicamente a CodexRadar para obtener recomendaciones de la comunidad.\r\n\r\nNo envía tu Codex Token, datos de uso ni contenido de proyectos. Como en cualquier solicitud a un sitio web, CodexRadar puede ver información de red habitual, como tu dirección IP y el User-Agent.\r\n\r\n¿Activar CodexRadar?",
    radar_speed_recommendation: "Velocidad",
    radar_smart_recommendation: "Inteligencia",
    radar_daily_development: "Recomendaciones para desarrollo diario",
    radar_intelligence_weighted: "Prioridad IQ",
    radar_tooltip_header:
        "CodexRadar · Actualizado hace {age} · Recomendación comunitaria no personalizada",
    radar_cached_warning: "Datos en caché · Pueden estar desactualizados",
    radar_loading: "Obteniendo recomendaciones de CodexRadar...",
    radar_data_unavailable: "Datos temporalmente no disponibles",
    radar_fetch_error: "No se pudieron obtener las recomendaciones de CodexRadar",
    radar_no_eligible: "No hay combinaciones con IQ ≥ 90",
};
