use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "透過 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex 使用量監控",
    refresh: "重新整理",
    update_frequency: "更新頻率",
    one_minute: "1 分鐘",
    five_minutes: "5 分鐘",
    fifteen_minutes: "15 分鐘",
    one_hour: "1 小時",
    codex_model: "Codex",
    settings: "設定",
    usage_display: "使用量顯示",
    usage_windows: "使用量視窗",
    used_usage: "已使用",
    remaining_usage: "剩餘",
    start_with_windows: "開機時啟動",
    reset_position: "重置位置",
    compact_mode: "緊湊模式",
    language: "語言",
    system_default: "系統預設",
    check_for_updates: "檢查更新",
    checking_for_updates: "正在檢查更新...",
    updates: "更新",
    update_in_progress: "已有更新檢查正在進行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "無法自動更新",
    applying_update: "正在套用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "結束",
    show_widget: "顯示小工具",
    show_5hour_window: "5 小時限額（已淘汰）",
    show_7day_window: "7 天限額",
    no_data: "無資料",
    session_window: "5h",
    weekly_window: "7d",
    now: "現在",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body:
        "請在終端機中執行 'codex'，並依照登入提示操作。完成後，請重新整理或重新啟動此應用程式。",
    second_suffix: "秒",
    codex_radar_menu: "CodexRadar",
    enable_codex_radar: "啟用 CodexRadar",
    refresh_codex_radar: "立即重新整理推薦資料",
    view_codex_radar_website: "查看網站",
    codex_radar_consent_title: "啟用 CodexRadar？",
    codex_radar_consent_body: "啟用後，本應用程式將定期連線至 CodexRadar，以取得社群推薦資料。\r\n\r\n請求不會傳送 Codex Token、用量資料或專案內容。與一般網站請求相同，CodexRadar 仍可看到 IP 位址、User-Agent 等常規網路資訊。\r\n\r\n是否啟用 CodexRadar？",
    radar_recommendation: "雷達推薦",
    radar_iq_per_dollar: "IQ/$",
    radar_intelligence_weighted: "偏智力",
    radar_tooltip_header: "CodexRadar · {age}前更新 · 非個人化社群推薦",
    radar_cached_warning: "快取資料 · 可能已過期",
    radar_loading: "正在取得雷達推薦資料...",
    radar_data_unavailable: "資料暫時無法使用",
    radar_fetch_error: "雷達推薦資料取得異常",
    radar_no_eligible: "暫無符合 IQ ≥ 90 的組合",
    radar_just_now: "剛剛",
};
